namespace: da-mno

envVars:
  NODE_ENV: production
  APP_ENV: production
  SYSTEM_PORT: 3000
  SYSTEM_HOST: 0.0.0.0
  NEXT_PUBLIC_API_BASE_URL: "https://billing-api.orion.mercury.dadanadagroup.com"
  NEXT_PUBLIC_SMS_API_BASE_URL: "https://sms-service.orion.mercury.dadanada-group.com"
  LOGSTASH_ENDPOINT: logstash-logstash.logging.svc.cluster.local:4560

redis:
  enabled: false

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

ingress:
  hosts:
    - sms-portal.orion.mercury.dadanadagroup.com

probes:
  readiness:
    path: /
    timeoutSeconds: 5
    initialDelaySeconds: 30
  liveness:
    path: /
    timeoutSeconds: 5
    initialDelaySeconds: 60
